<a href="https://colab.research.google.com/github/JaymersonFerreira/tratar-valores-vazios/blob/main/limpeza_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Identificando valores vazios

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("clientes.csv")
display(df)

#se tiver algum dados que nÃ£o seja nÃºmero, subistitua por vazio
df["TotalGasto"] = pd.to_numeric(df["TotalGasto"], errors="coerce")

# info
print(df.info())
# df.isna().any() ou .sum
#Mostra quando se a valores vazios na tabela
# print(df.isna().any())
print(df.isna().sum())

,IDCliente,Dependentes,MesesComoCliente,TipoContrato,FormaPagamento,TotalGasto
0,7010-BRBUU,Sim,72.0,2 anos,CartaoCredito,1734.65
1,9688-YGXVR,Nao,NaN,Mensal,CartaoCredito,3973.2
2,9286-DOJGF,Nao,NaN,Mensal,DebitoAutomatico,2869.85
3,6994-KERXL,Nao,4.0,Mensal,BoletoEletronico,238.5
4,2181-UAESM,Nao,2.0,Mensal,BoletoEletronico,119.5
...,...,...,...,...,...,...
5981,0684-AOSIH,Nao,1.0,Mensal,BoletoEletronico,95
5982,5982-PSMKW,Sim,23.0,2 anos,CartaoCredito,2198.3
5983,8044-BGWPI,Sim,12.0,Mensal,BoletoEletronico,306.05
5984,7450-NWRTR,Nao,12.0,Mensal,BoletoEletronico,1200.15
5985,4795-UXVCJ,Nao,26.0,Anual,CartaoCredito,457.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDCliente         5986 non-null   object
 1   Dependentes       5985 non-null   object
 2   MesesComoCliente  5984 non-null   float64
 3   TipoContrato      5986 non-null   object
 4   FormaPagamento    5986 non-null   object
 5   TotalGasto        5976 non-null   float64
dtypes: float64(2), object(4)
memory usage: 280.7+ KB
None
IDCliente            0
Dependentes          1
MesesComoCliente     2
TipoContrato         0
FormaPagamento       0
TotalGasto          10
dtype: int64

# Valores vazios nÃ£o identificaados como vazio

In [ ]:
# identifica na hora de importar
# valores_vazios = ["?","-"]
# df = pd.read_csv("clientes.csv", na_values=valores_vazios)



# identifica com replace
#
df = df.replace({"?": np.nan, "-": np.nan})
display(df)

,IDCliente,Dependentes,MesesComoCliente,TipoContrato,FormaPagamento,TotalGasto
0,7010-BRBUU,Sim,72.0,2 anos,CartaoCredito,1734.65
1,9688-YGXVR,Nao,NaN,Mensal,CartaoCredito,3973.20
2,9286-DOJGF,Nao,NaN,Mensal,DebitoAutomatico,2869.85
3,6994-KERXL,Nao,4.0,Mensal,BoletoEletronico,238.50
4,2181-UAESM,Nao,2.0,Mensal,BoletoEletronico,119.50
...,...,...,...,...,...,...
5981,0684-AOSIH,Nao,1.0,Mensal,BoletoEletronico,95.00
5982,5982-PSMKW,Sim,23.0,2 anos,CartaoCredito,2198.30
5983,8044-BGWPI,Sim,12.0,Mensal,BoletoEletronico,306.05
5984,7450-NWRTR,Nao,12.0,Mensal,BoletoEletronico,1200.15
5985,4795-UXVCJ,Nao,26.0,Anual,CartaoCredito,457.30

# Removendo valores vazios

In [ ]:
# joga fora o valor vazio
# dropna()

# 0 -> exclui linhas, 1 ->exclui colunas
# all -> quando todos os valores estiverem vazios
# any -> quando tiver algum um dado vazio
df = df.dropna(how='any', axis=0)

# Tratar valores vazios
- Preenchendo com valores fixo

In [ ]:
media = df["MesesComoCliente"].mean()
df["MesesComoCliente"] = df["MesesComoCliente"].fillna(media)
display(df)

,IDCliente,Dependentes,MesesComoCliente,TipoContrato,FormaPagamento,TotalGasto
0,7010-BRBUU,Sim,72.0,2 anos,CartaoCredito,1734.65
3,6994-KERXL,Nao,4.0,Mensal,BoletoEletronico,238.50
4,2181-UAESM,Nao,2.0,Mensal,BoletoEletronico,119.50
5,4312-GVYNH,Nao,70.0,2 anos,DebitoAutomatico,3370.20
6,2495-KZNFB,Nao,33.0,Mensal,BoletoEletronico,2989.60
...,...,...,...,...,...,...
5981,0684-AOSIH,Nao,1.0,Mensal,BoletoEletronico,95.00
5982,5982-PSMKW,Sim,23.0,2 anos,CartaoCredito,2198.30
5983,8044-BGWPI,Sim,12.0,Mensal,BoletoEletronico,306.05
5984,7450-NWRTR,Nao,12.0,Mensal,BoletoEletronico,1200.15
5985,4795-UXVCJ,Nao,26.0,Anual,CartaoCredito,457.30

32.51414699480998

- Preenchendo com anterior ou seguinte

In [ ]:
df["MesesComoCliente"] = df["MesesComoCliente"].fillna(method="ffill")
display(df)

,IDCliente,Dependentes,MesesComoCliente,TipoContrato,FormaPagamento,TotalGasto
0,7010-BRBUU,Sim,72.0,2 anos,CartaoCredito,1734.65
1,9688-YGXVR,Nao,72.0,Mensal,CartaoCredito,3973.20
2,9286-DOJGF,Nao,72.0,Mensal,DebitoAutomatico,2869.85
3,6994-KERXL,Nao,4.0,Mensal,BoletoEletronico,238.50
4,2181-UAESM,Nao,2.0,Mensal,BoletoEletronico,119.50
...,...,...,...,...,...,...
5981,0684-AOSIH,Nao,1.0,Mensal,BoletoEletronico,95.00
5982,5982-PSMKW,Sim,23.0,2 anos,CartaoCredito,2198.30
5983,8044-BGWPI,Sim,12.0,Mensal,BoletoEletronico,306.05
5984,7450-NWRTR,Nao,12.0,Mensal,BoletoEletronico,1200.15
5985,4795-UXVCJ,Nao,26.0,Anual,CartaoCredito,457.30

- Interpolando

In [ ]:
df["MesesComoCliente"] = df["MesesComoCliente"].interpolate()
display(df)

,IDCliente,Dependentes,MesesComoCliente,TipoContrato,FormaPagamento,TotalGasto
0,7010-BRBUU,Sim,72.000000,2 anos,CartaoCredito,1734.65
1,9688-YGXVR,Nao,49.333333,Mensal,CartaoCredito,3973.20
2,9286-DOJGF,Nao,26.666667,Mensal,DebitoAutomatico,2869.85
3,6994-KERXL,Nao,4.000000,Mensal,BoletoEletronico,238.50
4,2181-UAESM,Nao,2.000000,Mensal,BoletoEletronico,119.50
...,...,...,...,...,...,...
5981,0684-AOSIH,Nao,1.000000,Mensal,BoletoEletronico,95.00
5982,5982-PSMKW,Sim,23.000000,2 anos,CartaoCredito,2198.30
5983,8044-BGWPI,Sim,12.000000,Mensal,BoletoEletronico,306.05
5984,7450-NWRTR,Nao,12.000000,Mensal,BoletoEletronico,1200.15
5985,4795-UXVCJ,Nao,26.000000,Anual,CartaoCredito,457.30